### PR TITLE
Uberdog fix and other fixes when starting up

### PR DESCRIPTION
**Pull request by DarthMDev**

### CODE REVIEW

**Comment by DarthMDev** [comment]
@RegDogg can you review this when you can

**Comment by RegDogg** [comment]
I can take a look tomorrow, I'm about to leave for work

**Comment by RegDogg** [comment]
I have reviewed the PR, and decided not to merge, reason being that in Python 3.9 (TTR-Privates main version) the encoded cookie for UberDog is basically required, if you can give me some logs referring to what the UD server is crashing from, I will re-open this PR.

**Comment by DarthMDev** [comment]
Weird i am using python 3.9

**Comment by DarthMDev** [comment]
Actually i think its ur panda3d which is different that causes these crashes on open tt panda3d , which i didnt have access to before bc the link

**Comment by MichaelGDev48** [comment]
i reverted the CSMUD fix , only needed the whitelist fix can you check this again @RegDogg

**Pull request closed without merging**
